---
version: "3.3"
services:
  app:
    image: locally_built_dashboard_app
    env_file: .env.local
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:12.4-alpine
    env_file: .env.local
    volumes:
      - psql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  psql:

networks:
  frontend:
    external:
      name: proxy
  backend:
