---
version: "3.3"
services:
  dash-app:
    build:
      context: .
      network: backend
    env_file: .env.local
    restart: unless-stopped
    depends_on:
      - dash-db
    networks:
      - public
      - backend

  dash-db:
    image: postgres:12.4-alpine
    env_file: .env.local
    volumes:
      - psql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  psql:

networks:
  public:
    name: proxy
    external: true
  backend:
